### ISSUE TITLE
Error while connecting

### ISSUE THREAD

**Issue by mayuri2307** [pmbanugo/realtime-chartjs-hamoni#1]
![image](https://user-images.githubusercontent.com/31414105/98542493-09943700-22b7-11eb-8bdd-30217a27fa42.png)

Hi,
I am having this error when I run npm start. What is this error and how can I resolve it? I have been trying for 3 days but unable to resolve it.
Thanks!

**Comment by pmbanugo** [comment]
Hi,

Sorry for that. this repo and the accompanying blog hasn't been updated. It uses an old version of the library but the authentication method has changed to use JWT which the new package version supports.

You can check the [doc here](https://docs.hamoni.tech/sdk-usage/initialisation.html) for how to initialise it with a token and the rest should just work. 

This is a more recent one but written in vue. [Link](https://dev.to/pmbanugo/real-time-kanban-board-with-vuejs-and-hamoni-sync-52kg)

**Comment by mayuri2307** [comment]
> Hi,
> 
> Sorry for that. this repo and the accompanying blog hasn't been updated. It uses an old version of the library but the authentication method has changed to use JWT which the new package version supports.
> 
> You can check the [doc here](https://docs.hamoni.tech/sdk-usage/initialisation.html) for how to initialise it with a token and the rest should just work.
> 
> This is a more recent one but written in vue. [Link](https://dev.to/pmbanugo/real-time-kanban-board-with-vuejs-and-hamoni-sync-52kg)

Hey thanks for the information. I tried the same thing but it is still showing the same error.
![image](https://user-images.githubusercontent.com/31414105/98642269-2b42fc00-2353-11eb-9242-c7bbe2731439.png)
Below "app listening on port 5000!", the string written is the token generated. I printed the token on the console to see if the token is being generated or not. So, the token is coming but then it is not connecting to hamoni sync.
![image](https://user-images.githubusercontent.com/31414105/98642404-7230f180-2353-11eb-9074-28cd85befd30.png)

Can you help in figuring out the error? 
Thanks!!

**Comment by pmbanugo** [comment]
Hi @mayuri2307 

I'll check and let you know.

**Comment by pmbanugo** [comment]
Hi @mayuri2307 

I upgraded the version to 1.1.1 and updated the code to reflect the new auth style. It should work now when you get the latest changes.

**Comment by mayuri2307** [comment]
> Hi @mayuri2307
> 
> I upgraded the version to 1.1.1 and updated the code to reflect the new auth style. It should work now when you get the latest changes.

Hey! Thanks a lot for your efforts. It is now getting connected to Hamoni sync but it is not creating the state. I have gone through the doc as well. 
![image](https://user-images.githubusercontent.com/31414105/98780577-ff8b4900-241a-11eb-87bf-1c9b7bd3b6da.png)

The same error is coming on the Hamoni-sync dashboard.
Could you help me with the issue?
Thanks again for your time and efforts!
It is really a good project to work upon :)

**Comment by pmbanugo** [comment]
@mayuri2307  it's easier if you share your code. a few things to check is if you're creating state with a name that you've already used, or retrieving state that's not available

**Comment by mayuri2307** [comment]
> @mayuri2307 it's easier if you share your code. a few things to check is if you're creating state with a name that you've already used, or retrieving state that's not available

Hi, I have clones exactly your repository and have run the commands npm install, added my credentials, and then run npm start. I haven't changed anything yet. I have just done two changes. One was using of fetch requires an additional statement, const fetch = require("node-fetch"); and since the hamoni was declared inside async, so it wasn't accessible in create and get state functions. So for that, I declared the hamoni variable outside the function aync.
 But if you still want to see the folder, here's a link to it.
https://drive.google.com/drive/folders/1aJaJZgQFRIRyMymJlMIT5Jqc7GWE200v?usp=sharing
And this is the error on the dashboard.
![image](https://user-images.githubusercontent.com/31414105/98844729-c252a580-2472-11eb-8c02-d945ddf07542.png)

Thanks for helping out!

**Comment by alarinn** [comment]
I've been looking at Hamoni Sync for several weeks and I think the service no longer exists.  I'm assuming there is no work around for this?  I was able to create my user in the dashboard, but I get 'Our service is no longer available' upon logging in.  I followed the steps to make sure I'm doing things correctly.  Without the ability to login, you can't setup applications and without that you are dead in the water.

**Comment by pmbanugo** [comment]
Yes, it's no longer available.
